name: Build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
    types: [opened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node and install deps
        uses: ./.github/actions/node-setup
      - name: Lint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node and install deps
        uses: ./.github/actions/node-setup
      - name: Test
        run: yarn test
  build:
    needs: [lint, test]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node and install deps
        uses: ./.github/actions/node-setup
      - name: Build
        run: yarn build
